### ISSUE TITLE
H23Q related. urgent!

### ISSUE THREAD

**Issue by 2654400439** [efchatz/HTTP3-attacks#1]
Hello, Efstratios Chatzoglou, 
<br/>
    this is Yifei Cheng from the Institute of Information Engineering, Chinese Academy of Sciences. I am honored to read your paper on QUIC security-related topics -- 《A hands-on gaze on HTTP/3 security through the lens of HTTP/2 and a public dataset》.  
<br/>
    Our team is also currently working on anomaly detection for the QUIC protocol, but we have been making slow progress due to data collection issues. We are excited to see that you have made the dataset related to your paper public and recognize your open source spirit.  
<br/>
    However, after two days of trying, we found that we were never able to access the website for the public dataset you mentioned in your paper(https://icsdweb.aegean.gr/awid/other-datasets/H23Q). Even we found that Google's DNS is currently unable to resolve the site's second-level domain name.  
<br/>
    With no offense, is there a problem with our access, or is the site currently experiencing some problems? Has anyone else reported this to you? Actually, we are currently in need of this data and would appreciate it if you could tell me where and how to get this dataset!   
<br/>
    We look forward to your reply, thanks!

**Comment by efchatz** [comment]
Hello Yifei Cheng,

Thank you for your interest in our research. No offense at all. Unfortunately, the website's server is having some technical issues for the last two days. So, for this reason, this website is down. I believe that the relevant IT dept of the University will be able to solve the problem in the next few days. 

I can inform you when the website will be available again.

**Comment by 2654400439** [comment]
oops, what a pity! Please let me know as soon as the site is available, I would be very grateful!

**Comment by efchatz** [comment]
Sure, no problem. I will inform you as soon as the site is available again.

**Comment by efchatz** [comment]
Hello, it seems that the website is back online. Can you please make a try to request the datasets you need and let me know?

Thank you.

**Comment by 2654400439** [comment]
Yes, I can now access the download site, thank you very much!
